# Generated by Django 3.2.3 on 2021-05-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markers',
            name='avg_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='markers',
            name='beds_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='markers',
            name='care_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='markers',
            name='covid_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='markers',
            name='financial_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='markers',
            name='size',
            field=models.IntegerField(choices=[(0, 'small'), (1, 'medium'), (2, 'large')], default=0),
        ),
    ]
