# Generated by Django 3.2 on 2021-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210516_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='markers',
            name='oxygen_rating',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AddField(
            model_name='markers',
            name='ventilator_availability',
            field=models.BooleanField(default=0),
        ),
    ]
