# Generated by Django 3.2.3 on 2021-05-27 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='markers',
            name='datef',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='markers',
            name='icu_availability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='markers',
            name='oxygen_availability',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='markers',
            name='place_id',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='reviews',
            name='avg_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='datef',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='reviews',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='icu_availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviews',
            name='oxygen_availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='markers',
            name='care_rating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='markers',
            name='covid_rating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='markers',
            name='financial_rating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='markers',
            name='oxygen_rating',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='markers',
            name='ventilator_availability',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='beds_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='ventilator_availability',
            field=models.IntegerField(default=0),
        ),
    ]
