# Generated by Django 3.2.3 on 2021-05-29 13:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_auto_20210527_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='markers',
            name='Suspicious',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='markers',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='markers',
            name='hospital_pic',
            field=models.ImageField(blank=True, upload_to='hospital_pic'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='written_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Suspicious',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('datef', models.DateField(default=datetime.date.today)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.markers')),
            ],
        ),
        migrations.CreateModel(
            name='Review_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='review_pic')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.reviews')),
            ],
        ),
    ]
