# Generated by Django 3.2.3 on 2021-05-29 13:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_auto_20210529_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suspicious',
            new_name='SuspiciousMarking',
        ),
    ]
